[package]
name = "colony"
version = "0.1.0"
authors = ["Jack Wrenn <me@jswrenn.com>"]

[dependencies]
chrono          = "0.3.1"
error-chain     = "0.10.0"
itertools       = "0.6.0"
hyper           = "0.10.10"
select          = "0.4.0"


