[package]
name = "colony"
version = "0.1.0"
authors = ["Jack Wrenn <me@jswrenn.com>"]

[dependencies]
error-chain     = "0.10.0"
itertools       = "0.6.0"
hyper           = "0.10.10"
select          = "0.4.0"
serde           = "1.0"
serde_derive    = "1.0"
serde_json      = "1.0"



